name = "access-jwt"
main = "src/index.js"
compatibility_date = "2024-03-07"
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]

[[routes]]
pattern = "access-jwt.jldec.me"
zone_name = "jldec.me"
custom_domain = true
